spring:
    mail:
        host: smtp.gmail.com
        port: 587
        username: hasanjonovazamat@gmail.com
        password: evsotkafvokocffq
        properties:
            mjaail:
                smtp:
                    auth: true
            mail:
                smtp:
                    starttls:
                    enable: true
